"""backtest engine sprint 2 columns

Revision ID: 39c61437491e
Revises: d5aaa7039c4f
Create Date: 2026-07-02 01:36:02.511923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c61437491e'
down_revision: Union[str, Sequence[str], None] = 'd5aaa7039c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('backtests', sa.Column('symbol', sa.String(length=32), nullable=True))
    op.add_column('backtests', sa.Column('timeframe', sa.String(length=16), nullable=True))
    op.add_column('backtests', sa.Column('results', sa.JSON(), nullable=True))
    op.add_column('backtests', sa.Column('error_message', sa.Text(), nullable=True))
    op.create_index(op.f('ix_backtests_symbol'), 'backtests', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtests_symbol'), table_name='backtests')
    op.drop_column('backtests', 'error_message')
    op.drop_column('backtests', 'results')
    op.drop_column('backtests', 'timeframe')
    op.drop_column('backtests', 'symbol')
    op.drop_column('backtests', 'sortino_ratio')
    # ### end Alembic commands ###
