"""paper trading engine sprint 3

Revision ID: 5bad4f6e49ca
Revises: 39c61437491e
Create Date: 2026-07-02 04:00:20.971569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.infrastructure.database.types


# revision identifiers, used by Alembic.
revision: str = '5bad4f6e49ca'
down_revision: Union[str, Sequence[str], None] = '39c61437491e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_trading_sessions',
    sa.Column('portfolio_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tick_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_tick_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tick_count', sa.Integer(), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trading_sessions_portfolio_id'), 'paper_trading_sessions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_paper_trading_sessions_status'), 'paper_trading_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_paper_trading_sessions_user_id'), 'paper_trading_sessions', ['user_id'], unique=False)
    op.create_table('paper_trading_session_items',
    sa.Column('session_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('strategy_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['paper_trading_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trading_session_items_session_id'), 'paper_trading_session_items', ['session_id'], unique=False)
    op.create_index(op.f('ix_paper_trading_session_items_strategy_id'), 'paper_trading_session_items', ['strategy_id'], unique=False)
    op.add_column('positions', sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('positions', sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'take_profit')
    op.drop_column('positions', 'stop_loss')
    op.drop_index(op.f('ix_paper_trading_session_items_strategy_id'), table_name='paper_trading_session_items')
    op.drop_index(op.f('ix_paper_trading_session_items_session_id'), table_name='paper_trading_session_items')
    op.drop_table('paper_trading_session_items')
    op.drop_index(op.f('ix_paper_trading_sessions_user_id'), table_name='paper_trading_sessions')
    op.drop_index(op.f('ix_paper_trading_sessions_status'), table_name='paper_trading_sessions')
    op.drop_index(op.f('ix_paper_trading_sessions_portfolio_id'), table_name='paper_trading_sessions')
    op.drop_table('paper_trading_sessions')
    # ### end Alembic commands ###
