"""live trading engine sprint 4 broker account fields

Revision ID: d2f8a40596be
Revises: 5bad4f6e49ca
Create Date: 2026-07-04 15:16:18.105261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f8a40596be'
down_revision: Union[str, Sequence[str], None] = '5bad4f6e49ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand: autogenerate omits it, but a NOT NULL
    # column added to a table with existing rows is rejected outright by
    # Postgres without one to backfill existing rows (verified against a
    # real Postgres instance with a pre-existing row before this fix).
    op.add_column(
        'broker_accounts',
        sa.Column('live_trading_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('broker_accounts', sa.Column('last_health_check_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('broker_accounts', sa.Column('last_connection_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker_accounts', 'last_connection_error')
    op.drop_column('broker_accounts', 'last_health_check_at')
    op.drop_column('broker_accounts', 'live_trading_enabled')
    # ### end Alembic commands ###
