"""initial schema

Revision ID: d5aaa7039c4f
Revises: 
Create Date: 2026-07-01 19:10:55.623553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.infrastructure.database.types


# revision identifiers, used by Alembic.
revision: str = 'd5aaa7039c4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_logs',
    sa.Column('module', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_module'), 'system_logs', ['module'], unique=False)
    op.create_index(op.f('ix_system_logs_severity'), 'system_logs', ['severity'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('broker_accounts',
    sa.Column('user_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('broker_name', sa.String(length=64), nullable=False),
    sa.Column('account_number', sa.String(length=128), nullable=True),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('encrypted_api_key', sa.String(length=512), nullable=True),
    sa.Column('encrypted_secret', sa.String(length=512), nullable=True),
    sa.Column('encrypted_password', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_accounts_user_id'), 'broker_accounts', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('user_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('equity', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('margin_used', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('free_margin', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('kill_switch_active', sa.Boolean(), nullable=False),
    sa.Column('peak_equity', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('user_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_risk', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notification_preferences', sa.JSON(), nullable=False),
    sa.Column('risk_settings', sa.JSON(), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_user_id'), 'settings', ['user_id'], unique=True)
    op.create_table('strategies',
    sa.Column('user_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_class', sa.String(length=32), nullable=True),
    sa.Column('timeframe', sa.String(length=16), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_status'), 'strategies', ['status'], unique=False)
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('user_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('backtests',
    sa.Column('strategy_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('dataset', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initial_balance', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('ending_balance', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('expectancy', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('report_location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtests_strategy_id'), 'backtests', ['strategy_id'], unique=False)
    op.create_table('equity_history',
    sa.Column('portfolio_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('equity', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('drawdown', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equity_history_portfolio_id'), 'equity_history', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_equity_history_timestamp'), 'equity_history', ['timestamp'], unique=False)
    op.create_table('orders',
    sa.Column('portfolio_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('broker_account_id', app.infrastructure.database.types.GUID(), nullable=True),
    sa.Column('strategy_id', app.infrastructure.database.types.GUID(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('requested_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('executed_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('broker_order_id', sa.String(length=128), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_portfolio_id'), 'orders', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_strategy_id'), 'orders', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('performance_reports',
    sa.Column('strategy_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('report_name', sa.String(length=255), nullable=False),
    sa.Column('report_path', sa.String(length=512), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_reports_strategy_id'), 'performance_reports', ['strategy_id'], unique=False)
    op.create_table('positions',
    sa.Column('portfolio_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_portfolio_id'), 'positions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('risk_events',
    sa.Column('portfolio_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('action_taken', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_event_type'), 'risk_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_risk_events_portfolio_id'), 'risk_events', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_risk_events_timestamp'), 'risk_events', ['timestamp'], unique=False)
    op.create_table('signals',
    sa.Column('strategy_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('signal_type', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_strategy_id'), 'signals', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('trades',
    sa.Column('strategy_id', app.infrastructure.database.types.GUID(), nullable=True),
    sa.Column('order_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('position_id', app.infrastructure.database.types.GUID(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('commission', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('spread_cost', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('slippage_cost', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('trade_duration', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_order_id'), 'trades', ['order_id'], unique=False)
    op.create_index(op.f('ix_trades_position_id'), 'trades', ['position_id'], unique=False)
    op.create_index(op.f('ix_trades_strategy_id'), 'trades', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_position_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_order_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_strategy_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_risk_events_timestamp'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_portfolio_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_event_type'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_index(op.f('ix_positions_portfolio_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_performance_reports_strategy_id'), table_name='performance_reports')
    op.drop_table('performance_reports')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_strategy_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_portfolio_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_equity_history_timestamp'), table_name='equity_history')
    op.drop_index(op.f('ix_equity_history_portfolio_id'), table_name='equity_history')
    op.drop_table('equity_history')
    op.drop_index(op.f('ix_backtests_strategy_id'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_status'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_settings_user_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_broker_accounts_user_id'), table_name='broker_accounts')
    op.drop_table('broker_accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_logs_severity'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_module'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_table('system_logs')
    # ### end Alembic commands ###
